use super::Opcode;

pub(super) fn is_opcode(op: Opcode) -> bool {
    matches!(
        op,
        Opcode::SveCnt
            | Opcode::SveAddvl
            | Opcode::SveAddsvl
            | Opcode::SveAddpl
            | Opcode::SveAddspl
            | Opcode::SveRdvl
            | Opcode::SveRdsvl
            | Opcode::SveIncScalar
            | Opcode::SveDecScalar
            | Opcode::SveIncpScalar
            | Opcode::SveDecpScalar
            | Opcode::SveIncpVector
            | Opcode::SveDecpVector
            | Opcode::SveIncPatternVector
            | Opcode::SveDecPatternVector
            | Opcode::SveCntp
            | Opcode::SvePtrue
            | Opcode::SvePtrues
            | Opcode::SvePtest
            | Opcode::SvePredAnd
            | Opcode::SvePredBic
            | Opcode::SvePredOrr
            | Opcode::SvePredOrn
            | Opcode::SvePredEor
            | Opcode::SvePredNor
            | Opcode::SvePredNand
            | Opcode::SveMovprfx
            | Opcode::SveDupGpr
            | Opcode::SveDupImm
            | Opcode::SveDupElem
            | Opcode::SveCpyImm
            | Opcode::SveCpyGpr
            | Opcode::SveAddVec
            | Opcode::SveSubVec
            | Opcode::SveMla
            | Opcode::SveMls
            | Opcode::SveMad
            | Opcode::SveMsb
            | Opcode::SveAddImm
            | Opcode::SveSubImm
            | Opcode::SveAddPred
            | Opcode::SveSubPred
            | Opcode::SveAndVec
            | Opcode::SveAndPred
            | Opcode::SveOrrPred
            | Opcode::SveEorPred
            | Opcode::SveAsrImm
            | Opcode::SveLsrImm
            | Opcode::SveLslImm
            | Opcode::SveXar
            | Opcode::SveUunpklo
            | Opcode::SveUunpkhi
            | Opcode::SveSunpklo
            | Opcode::SveSunpkhi
            | Opcode::SvePunpklo
            | Opcode::SvePunpkhi
            | Opcode::SveZip1
            | Opcode::SveZip2
            | Opcode::SveUzp1
            | Opcode::SveUzp2
            | Opcode::SveUqadd
            | Opcode::SveTbl
            | Opcode::SveRevh
            | Opcode::SveIndex
            | Opcode::SveOrrVec
            | Opcode::SveEorVec
            | Opcode::SveAndImm
            | Opcode::SveOrrImm
            | Opcode::SveEorImm
            | Opcode::SveDupm
            | Opcode::SveSel
            | Opcode::SveCmpHs
            | Opcode::SveCmpHsImm
            | Opcode::SveCmpHi
            | Opcode::SveCmpHiImm
            | Opcode::SveCmpEq
            | Opcode::SveCmpEqImm
            | Opcode::SveCmpNe
            | Opcode::SveCmpNeImm
            | Opcode::SveWhileLo
            | Opcode::SveWhileLt
            | Opcode::SveWhileLe
            | Opcode::SveWhileLs
            | Opcode::SveWhileGe
            | Opcode::SveWhileGt
            | Opcode::SveWhileHs
            | Opcode::SveWhileHi
            | Opcode::SveLdr
            | Opcode::SveStr
            | Opcode::SveLd1rd
            | Opcode::SveLd1rqd
            | Opcode::SveLd1d
            | Opcode::SveSt1d
            | Opcode::SveSt1b
            | Opcode::SveLd1b
            | Opcode::SveSt1h
            | Opcode::SveSt1hScatter
            | Opcode::SveLd1h
            | Opcode::SveLdnt1sh
            | Opcode::SveLd1rw
            | Opcode::SveLd1rqw
            | Opcode::SveLd1w
            | Opcode::SveSt1w
            | Opcode::SveFpAdd
            | Opcode::SveFpAddImm
            | Opcode::SveFpSub
            | Opcode::SveFpMul
            | Opcode::SveFpDiv
            | Opcode::SveFpSubr
            | Opcode::SveFpDivr
            | Opcode::SveFpFmin
            | Opcode::SveFpFabd
            | Opcode::SveFpMulImm
            | Opcode::SveFpDupImm
            | Opcode::SveFpCpyImm
            | Opcode::SveFpFexpa
            | Opcode::SveFpFtmad
            | Opcode::SveFpFscale
            | Opcode::SveFpFtsmul
            | Opcode::SveFpFtssel
            | Opcode::SveFpAbs
            | Opcode::SveFpNeg
            | Opcode::SveFpSqrt
            | Opcode::SveFpFrintn
            | Opcode::SveFpFrinta
            | Opcode::SveFpFrintz
            | Opcode::SveScvtf
            | Opcode::SveFcvtzs
            | Opcode::SveFpFcvt
            | Opcode::SveFpFacge
            | Opcode::SveFpFacgt
            | Opcode::SveFpFcmeq
            | Opcode::SveFpFcmge
            | Opcode::SveFpFcmgt
            | Opcode::SveFpFcmne
            | Opcode::SveFpFcmle
            | Opcode::SveFpFcmlt
            | Opcode::SveFpFmla
            | Opcode::SveFpFmls
            | Opcode::SveFpFmad
            | Opcode::SveFpFmsb
            | Opcode::SveFpFnmla
            | Opcode::SveFpFnmls
            | Opcode::SveFpFnmad
            | Opcode::SveFpFnmsb
            | Opcode::SveFpFcmla
            | Opcode::SveFpFmlaIndex
            | Opcode::SveFpFmlsIndex
            | Opcode::SveFpMulIndex
    )
}
