//! Data-processing helpers: logical, bitfield, multiply, shift, bit manipulation, flags.

mod bitfield;
mod bitops;
mod condition;
mod flags;
mod fp_access;
mod fp_arithmetic;
mod fp_compare;
mod fp_compare_helpers;
mod fp_convert;
mod fp_half;
mod fp_immediate;
mod fp_round;
mod fp_rounding;
mod fp_scalar;
mod fp_unary;
mod multiply;
mod scalar_extend;
mod scalar_logical;
mod scalar_shift;
mod simd_crypto;
mod simd_crypto_helpers;
mod simd_crypto_tables;
mod simd_data;
mod simd_elementwise;
mod simd_fp;
mod simd_fp_compare;
mod simd_fp_convert;
mod simd_fp_fused;
mod simd_fp_minmax;
mod simd_fp_minmax_helpers;
mod simd_fp_pairwise;
mod simd_fp_reduce;
mod simd_fp_unary_more;
mod simd_integer;
mod simd_logic;
mod simd_masks;
mod simd_moves;
mod simd_pairwise;
mod simd_permute;
mod simd_reduce;
mod simd_reduce_helpers;
mod simd_shift;
mod simd_unary_compare;
mod simd_widen;

use super::{Instr, Opcode};
use crate::arm64::Armv8Cpu;
use crate::arm64::helpers::{cond_taken, read_reg, write_reg};
use crate::constants::*;

pub(super) use bitfield::*;
pub(super) use bitops::*;
pub(super) use condition::*;
pub(super) use flags::*;
pub(super) use fp_access::*;
pub(super) use fp_arithmetic::*;
pub(super) use fp_compare::*;
pub(super) use fp_compare_helpers::*;
pub(super) use fp_convert::*;
pub(super) use fp_half::*;
pub(super) use fp_immediate::*;
pub(super) use fp_round::*;
pub(super) use fp_rounding::*;
pub(super) use fp_scalar::*;
pub(super) use fp_unary::*;
pub(super) use multiply::*;
pub(super) use scalar_extend::*;
pub(super) use scalar_logical::*;
pub(super) use scalar_shift::*;
pub(super) use simd_crypto::*;
pub(super) use simd_crypto_helpers::*;
pub(super) use simd_crypto_tables::*;
pub(super) use simd_data::*;
pub(super) use simd_elementwise::*;
pub(super) use simd_fp::*;
pub(super) use simd_fp_compare::*;
pub(super) use simd_fp_convert::*;
pub(super) use simd_fp_fused::*;
pub(super) use simd_fp_minmax::*;
pub(super) use simd_fp_minmax_helpers::*;
pub(super) use simd_fp_pairwise::*;
pub(super) use simd_fp_reduce::*;
pub(super) use simd_fp_unary_more::*;
pub(super) use simd_integer::*;
pub(super) use simd_logic::*;
pub(super) use simd_masks::*;
pub(super) use simd_moves::*;
pub(super) use simd_pairwise::*;
pub(super) use simd_permute::*;
pub(super) use simd_reduce::*;
pub(super) use simd_reduce_helpers::*;
pub(super) use simd_shift::*;
pub(super) use simd_unary_compare::*;
pub(super) use simd_widen::*;
