use super::*;

pub(super) fn map(raw: u32, m: disarm64::decoder::Mnemonic) -> Option<Opcode> {
    use disarm64::decoder::Mnemonic as M;
    Some(match m {
        M::r#add
            if ((raw & 0xFF20_FC00) == 0x5E20_8400 && ((raw >> 22) & 0x3) == 0x3)
                || (raw & 0xBF20_FC00) == 0x0E20_8400 =>
        {
            Opcode::SimdAddVec
        }
        M::r#add if (raw & 0xFF20_FC00) == 0x0420_0000 => Opcode::SveAddVec,
        M::r#add => Opcode::Add,
        M::r#adds => Opcode::Adds,
        M::r#sub if (raw & 0xBF20_FC00) == 0x2E20_8400 => Opcode::SimdSubVec,
        M::r#sub if (raw & 0xFF20_FC00) == 0x0420_0400 => Opcode::SveSubVec,
        M::r#sub => Opcode::Sub,
        M::r#subs => Opcode::Subs,
        M::r#adc => Opcode::Adc,
        M::r#adcs => Opcode::Adcs,
        M::r#sbc => Opcode::Sbc,
        M::r#sbcs => Opcode::Sbcs,
        M::r#movz => Opcode::Movz,
        M::r#movk => Opcode::Movk,
        M::r#movn => Opcode::Movn,
        M::r#and if (raw & 0xBFE0_FC00) == 0x0E20_1C00 => Opcode::SimdAnd,
        M::r#and if (raw & 0xFFF0_C210) == 0x2500_4000 || (raw & 0xFFF0_C210) == 0x2540_4000 => {
            Opcode::SvePredAnd
        }
        M::r#and if (raw & 0x1F80_0000) == 0x1200_0000 => Opcode::AndImm,
        M::r#and => Opcode::AndReg,
        M::r#ands if (raw & 0xFFF0_C210) == 0x2540_4000 => Opcode::SvePredAnd,
        M::r#ands if (raw & 0x1F80_0000) == 0x1200_0000 => Opcode::AndsImm,
        M::r#ands => Opcode::AndsReg,
        M::r#bic if (raw & 0xBFE0_FC00) == 0x0E60_1C00 => Opcode::SimdBic,
        M::r#orr if (raw & 0xBFE0_FC00) == 0x0EA0_1C00 => Opcode::SimdOrr,
        M::r#orr if (raw & 0xFFE0_FC00) == 0x0460_3000 => Opcode::SveOrrVec,
        M::r#orr if (raw & 0xFFF0_C210) == 0x2580_4000 || (raw & 0xFFF0_C210) == 0x25C0_4000 => {
            Opcode::SvePredOrr
        }
        M::r#orr if (raw & 0x1F80_0000) == 0x1200_0000 => Opcode::OrrImm,
        M::r#orn if (raw & 0xBFE0_FC00) == 0x0EE0_1C00 => Opcode::SimdOrn,
        M::r#orrs if (raw & 0xFFF0_C210) == 0x25C0_4000 => Opcode::SvePredOrr,
        M::r#bsl if (raw & 0xBFE0_FC00) == 0x2E60_1C00 => Opcode::SimdBsl,
        M::r#bit if (raw & 0xBFE0_FC00) == 0x2EA0_1C00 => Opcode::SimdBit,
        M::r#bif if (raw & 0xBFE0_FC00) == 0x2EE0_1C00 => Opcode::SimdBif,
        M::r#orr => Opcode::OrrReg,
        M::r#eor if (raw & 0xFFE0_FC00) == 0x04A0_3000 => Opcode::SveEorVec,
        M::r#eor if (raw & 0x1F80_0000) == 0x1200_0000 => Opcode::EorImm,
        M::r#eor => Opcode::EorReg,
        M::r#csel => Opcode::Csel,
        M::r#csinc => Opcode::Csinc,
        M::r#csinv => Opcode::Csinv,
        M::r#csneg => Opcode::Csneg,
        M::r#ldr if matches!(raw & 0xFFC0_E000, 0x8580_0000 | 0x8580_4000) => Opcode::SveLdr,
        M::r#ldr if (raw & 0x3B00_0000) == 0x1800_0000 => Opcode::LdrLit,
        M::r#ldr | M::r#ldur if ((raw >> 26) & 1) != 0 => Opcode::SimdLdr,
        M::r#ldr | M::r#ldur => Opcode::Ldr,
        M::r#ld1rd if (raw & 0xFFC0_E000) == 0x85C0_E000 => Opcode::SveLd1rd,
        M::r#ld1rqd if (raw & 0xFFF0_E000) == 0xA580_2000 => Opcode::SveLd1rqd,
        M::r#ld1d if (raw & 0xFFE0_E000) == 0xC5E0_C000 || (raw & 0xFFF0_E000) == 0xA5E0_A000 => {
            Opcode::SveLd1d
        }
        M::r#st1d if (raw & 0xFFF0_E000) == 0xE5E0_E000 => Opcode::SveSt1d,
        M::r#ldrsw if (raw & 0x3B00_0000) == 0x1800_0000 => Opcode::LdrLit,
        M::r#ldrsw => Opcode::LdrSign,
        M::r#str if matches!(raw & 0xFFC0_E000, 0xE580_0000 | 0xE580_4000) => Opcode::SveStr,
        M::r#str | M::r#stur if ((raw >> 26) & 1) != 0 => Opcode::SimdStr,
        M::r#str | M::r#stur => Opcode::Str,
        M::r#ldp => Opcode::Ldp,
        M::r#stp => Opcode::Stp,
        M::r#ldxr => Opcode::Ldxr,
        M::r#ldar => Opcode::Ldar,
        M::r#stxr => Opcode::Stxr,
        M::r#stlr => Opcode::Stlr,
        M::r#swpp | M::r#swppa | M::r#swppal | M::r#swppl => Opcode::AtomicPair,
        M::r#ldsetp | M::r#ldsetpa | M::r#ldsetpal | M::r#ldsetpl => Opcode::AtomicPair,
        M::r#ldclrp | M::r#ldclrpa | M::r#ldclrpal | M::r#ldclrpl => Opcode::AtomicPair,
        M::r#ldxp => Opcode::Ldxp,
        M::r#stxp => Opcode::Stxp,
        M::r#b | M::r#b_ => Opcode::B,
        M::r#bl => Opcode::Bl,
        M::r#br => Opcode::Br,
        M::r#blr => Opcode::Blr,
        M::r#ret => Opcode::Ret,
        M::r#cbz => Opcode::Cbz,
        M::r#cbnz => Opcode::Cbnz,
        M::r#tbz => Opcode::Tbz,
        M::r#tbnz => Opcode::Tbnz,
        M::r#bc_ => Opcode::BCond,
        M::r#adr => Opcode::Adr,
        M::r#adrp => Opcode::Adrp,
        M::r#mrs => Opcode::Mrs,
        M::r#svc => Opcode::Svc,
        M::r#brk => Opcode::Brk,
        M::r#cntb | M::r#cnth | M::r#cntw | M::r#cntd => Opcode::SveCnt,
        M::r#addvl => Opcode::SveAddvl,
        M::r#addsvl => Opcode::SveAddsvl,
        M::r#ptrue => Opcode::SvePtrue,
        M::r#ptest => Opcode::SvePtest,
        M::r#movprfx => Opcode::SveMovprfx,
        M::r#eret => Opcode::Eret,
        M::r#hint => Opcode::Nop,
        M::r#mul if (raw & 0xBF20_FC00) == 0x0E20_9C00 => Opcode::SimdMulVec,
        M::r#mla if (raw & 0xBF20_FC00) == 0x0E20_9400 => Opcode::SimdMlaVec,
        M::r#madd | M::r#mul => Opcode::Madd,
        M::r#msub => Opcode::Msub,
        M::r#smulh => Opcode::Smulh,
        M::r#umulh => Opcode::Umulh,
        M::r#udiv => Opcode::Udiv,
        M::r#sdiv => Opcode::Sdiv,
        M::r#lsl | M::r#lslv => Opcode::Lslv,
        M::r#lsr | M::r#lsrv => Opcode::Lsrv,
        M::r#asr | M::r#asrv => Opcode::Asrv,
        M::r#rorv => Opcode::Rorv,
        M::r#rev => Opcode::Rev,
        M::r#rev16 if (raw & 0x7FFF_FC00) == 0x5AC0_0400 => Opcode::Rev16,
        M::r#rev32 if (raw & 0xFFFF_FC00) == 0xDAC0_0800 => Opcode::Rev32,
        M::r#rbit => Opcode::Rbit,
        M::r#clz => Opcode::Clz,
        M::r#crc32b | M::r#crc32h | M::r#crc32w | M::r#crc32x => Opcode::Crc32,
        M::r#sxtw => Opcode::Sxtw,
        M::r#ccmn => Opcode::Ccmn,
        M::r#ccmp => Opcode::Ccmp,
        M::r#sbfm if (raw & 0x7F80_0000) == 0x1300_0000 => Opcode::Sbfm,
        M::r#bfm if (raw & 0x7F80_0000) == 0x3300_0000 => Opcode::Bfm,
        M::r#ubfm if (raw & 0x7F80_0000) == 0x5300_0000 => Opcode::Ubfm,
        _ => return None,
    })
}
