use crate::arm64::Opcode;

pub(super) fn is_opcode(op: Opcode) -> bool {
    matches!(
        op,
        Opcode::SimdShrn
            | Opcode::SimdShrn2
            | Opcode::SimdRshrn
            | Opcode::SimdRshrn2
            | Opcode::SimdAddhn
            | Opcode::SimdAddhn2
            | Opcode::SimdRaddhn
            | Opcode::SimdRaddhn2
            | Opcode::SimdSubhn
            | Opcode::SimdSubhn2
            | Opcode::SimdRsubhn
            | Opcode::SimdRsubhn2
            | Opcode::SimdAddVec
            | Opcode::SimdSubVec
            | Opcode::SimdMulVec
            | Opcode::SimdMlaVec
            | Opcode::SimdMlsVec
            | Opcode::SimdAddp
            | Opcode::SimdAddv
            | Opcode::SimdSmaxv
            | Opcode::SimdSminv
            | Opcode::SimdUmaxv
            | Opcode::SimdUminv
            | Opcode::SimdExt
            | Opcode::SimdSmaxVec
            | Opcode::SimdSminVec
            | Opcode::SimdUmaxVec
            | Opcode::SimdUminVec
            | Opcode::SimdSmaxp
            | Opcode::SimdSminp
            | Opcode::SimdUmaxp
            | Opcode::SimdUminp
            | Opcode::SimdShlImm
            | Opcode::SimdSli
            | Opcode::SimdSri
            | Opcode::SimdSshr
            | Opcode::SimdUshr
            | Opcode::SimdUsra
            | Opcode::SimdSshl
            | Opcode::SimdUshl
            | Opcode::SimdXtn
            | Opcode::SimdXtn2
            | Opcode::SimdRev64
            | Opcode::SimdRev32
            | Opcode::SimdInsElem
            | Opcode::SimdUzp1
            | Opcode::SimdUzp2
            | Opcode::SimdTrn1
            | Opcode::SimdTrn2
            | Opcode::SimdZip1
            | Opcode::SimdZip2
            | Opcode::SimdTbl
            | Opcode::SimdTbx
            | Opcode::SimdNot
            | Opcode::SimdRbit
            | Opcode::SimdBsl
            | Opcode::SimdBit
            | Opcode::SimdBif
            | Opcode::SimdAnd
            | Opcode::SimdOrr
            | Opcode::SimdOrn
            | Opcode::SimdEor
            | Opcode::SimdBic
            | Opcode::SimdBicImm
            | Opcode::SimdMvni
            | Opcode::SimdUshll
            | Opcode::SimdSshll
            | Opcode::SimdShll
            | Opcode::SimdSaddl
            | Opcode::SimdUaddl
            | Opcode::SimdUsubl
            | Opcode::SimdSsubw
            | Opcode::SimdSaddw
            | Opcode::SimdUaddw
            | Opcode::SimdUsubw
            | Opcode::SimdUmlal
            | Opcode::SimdUmlsl
            | Opcode::SimdUmlalVec
            | Opcode::SimdUmull
            | Opcode::SimdUmullElem
    )
}
