export const els = {
  autoScroll: document.querySelector("#autoScroll"),
  bootDebian: document.querySelector("#bootDebian"),
  bootIso: document.querySelector("#bootIso"),
  clearDisk: document.querySelector("#clearDisk"),
  diskSize: document.querySelector("#diskSize"),
  diskValue: document.querySelector("#diskValue"),
  eventLog: document.querySelector("#eventLog"),
  isoFile: document.querySelector("#isoFile"),
  jitStatsValue: document.querySelector("#jitStatsValue"),
  pagesValue: document.querySelector("#pagesValue"),
  pauseVm: document.querySelector("#pauseVm"),
  pcValue: document.querySelector("#pcValue"),
  resetVm: document.querySelector("#resetVm"),
  resumeVm: document.querySelector("#resumeVm"),
  saveDisk: document.querySelector("#saveDisk"),
  savedValue: document.querySelector("#savedValue"),
  statusLine: document.querySelector("#statusLine"),
  stepSlice: document.querySelector("#stepSlice"),
  stepsValue: document.querySelector("#stepsValue"),
  terminal: document.querySelector("#terminal"),
  uartValue: document.querySelector("#uartValue"),
};
