use crate::arm64::Opcode;

pub(super) fn is_simd_data_opcode(op: Opcode) -> bool {
    matches!(
        op,
        Opcode::SimdAese
            | Opcode::SimdAesd
            | Opcode::SimdAesmc
            | Opcode::SimdAesimc
            | Opcode::SimdPmull
            | Opcode::SimdSha1h
            | Opcode::SimdSha256Su0
            | Opcode::SimdSha512Su0
            | Opcode::SimdSm4e
            | Opcode::SimdSm3Partw1
            | Opcode::SimdEor3
            | Opcode::SimdBcax
            | Opcode::SimdRax1
            | Opcode::SimdXar
            | Opcode::SimdDupByte
            | Opcode::SimdDupElem
            | Opcode::SimdFmovReg64
            | Opcode::SimdFmovGprToD
            | Opcode::SimdFmovGprToS
            | Opcode::SimdFmovDToGpr
            | Opcode::SimdFmovSToGpr
            | Opcode::SimdFmovLaneToGpr
            | Opcode::SimdFmovImm
            | Opcode::SimdUmov
            | Opcode::SimdSmov
            | Opcode::SimdInsGprLane
            | Opcode::SimdCmeqZero
            | Opcode::SimdCmgeZero
            | Opcode::SimdCmeqReg
            | Opcode::SimdCmhsReg
            | Opcode::SimdCmhiReg
            | Opcode::SimdShrn
            | Opcode::SimdAddhn
            | Opcode::SimdSubhn
            | Opcode::SimdAddVec
            | Opcode::SimdSubVec
            | Opcode::SimdMulVec
            | Opcode::SimdMlaVec
            | Opcode::SimdAddp
            | Opcode::SimdAddv
            | Opcode::SimdUmaxv
            | Opcode::SimdExt
            | Opcode::SimdSmaxVec
            | Opcode::SimdUmaxVec
            | Opcode::SimdUminVec
            | Opcode::SimdUmaxp
            | Opcode::SimdUminp
            | Opcode::SimdCnt
            | Opcode::SimdCmtst
            | Opcode::SimdShlImm
            | Opcode::SimdSli
            | Opcode::SimdSri
            | Opcode::SimdSshr
            | Opcode::SimdUshr
            | Opcode::SimdUshl
            | Opcode::SimdXtn
            | Opcode::SimdRev64
            | Opcode::SimdRev32
            | Opcode::SimdNot
            | Opcode::SimdBsl
            | Opcode::SimdBit
            | Opcode::SimdBif
            | Opcode::SimdAnd
            | Opcode::SimdOrr
            | Opcode::SimdOrn
            | Opcode::SimdEor
            | Opcode::SimdInsElem
            | Opcode::SimdUzp1
            | Opcode::SimdTrn1
            | Opcode::SimdZip1
            | Opcode::SimdZip2
            | Opcode::SimdTbl
            | Opcode::SimdBic
            | Opcode::SimdBicImm
            | Opcode::SimdMvni
            | Opcode::SimdUshll
            | Opcode::SimdSshll
            | Opcode::SimdShll
            | Opcode::SimdSaddl
            | Opcode::SimdUsubl
            | Opcode::SimdSsubw
            | Opcode::SimdUmlal
            | Opcode::SimdUqsub
            | Opcode::SimdAbs
            | Opcode::SimdNeg
            | Opcode::SimdScvtf
            | Opcode::SimdUcvtf
            | Opcode::SimdFcvtzs
            | Opcode::SimdFcvtzu
            | Opcode::SimdFcvtas
            | Opcode::SimdFpAddVec
            | Opcode::SimdFpSubVec
            | Opcode::SimdFpMulVec
            | Opcode::SimdFpDivVec
            | Opcode::SimdFpAbd
            | Opcode::SimdFpNeg
            | Opcode::SimdFpAbsVec
            | Opcode::SimdFpFrintaVec
            | Opcode::SimdFpSqrtVec
            | Opcode::SimdFpFacgeVec
            | Opcode::SimdFpFacgtVec
            | Opcode::SimdFpFcmgeVec
            | Opcode::SimdFpFcmgtVec
            | Opcode::SimdFpFcmeqZero
            | Opcode::SimdFpFcmleZero
            | Opcode::SimdFpFcmltZero
            | Opcode::SimdFpFmlaVec
            | Opcode::SimdFpFmlsVec
            | Opcode::SimdFpFmlaElem
            | Opcode::SimdFpFmlsElem
            | Opcode::SimdFpMulElem
    )
}
