use super::*;

mod adrp;
mod atomics;
mod basic_data;
mod branches_conditions;
mod busybox_crypto_fields;
mod busybox_fp_cases;
mod busybox_fp_fields;
mod busybox_simd_cases;
mod cmp_aliases;
mod cssc;
mod exclusive;
mod loads_literals;
mod logical_aliases;
mod mops;
mod mte;
mod multiply_long;
mod pairs_and_initial_simd;
mod scalar_aliases;
mod scalar_fp_minmax;
mod scalar_ldst;
mod scalar_rcpc_pair;
mod simd_alias_mappings;
mod simd_cmhs;
mod simd_compare_zero;
mod simd_fp_minmax;
mod simd_fp_mulx;
mod simd_fp_pairwise;
mod simd_fp_unary_more;
mod simd_fp_vector_convert;
mod simd_fp_zero_compare;
mod simd_ld4_single;
mod simd_minmax;
mod simd_modified_immediate;
mod simd_pairwise_narrow;
mod simd_permute_secondary;
mod simd_rbit;
mod simd_rcpc_ldst;
mod simd_reduce_across;
mod simd_scalar_bitwise_compare;
mod simd_saturating_add;
mod simd_sha1_sha256;
mod simd_sha512;
mod simd_shift_accumulate;
mod simd_shift_register;
mod simd_signed_compare;
mod simd_sm3;
mod simd_struct_store;
mod simd_ucvtf;
mod simd_userland_arith_move;
mod simd_userland_dup;
mod simd_userland_fp_imm_cmp;
mod simd_userland_ld1;
mod simd_userland_logical;
mod simd_userland_struct_ldst;
mod simd_userland_widen_fp;
mod simd_widen_addwide;
mod simd_widen_mul;
mod simd_xtn2;
mod sme_memory;
mod sme_matrix;
mod sve_addsub;
mod sve_byte_load_store;
mod sve_compare;
mod sve_counts;
mod sve_dup;
mod sve_fp_compare;
mod sve_fp_complex;
mod sve_fp_convert;
mod sve_fp_div;
mod sve_fp_fexpa;
mod sve_fp_immediate;
mod sve_fp_scale;
mod sve_fp_trig;
mod sve_fp_unary;
mod sve_fp_unpredicated;
mod sve_index;
mod sve_load_store;
mod sve_logical_imm;
mod sve_logical_pred;
mod sve_permute;
mod sve_predicate;
mod sve_reverse;
mod sve_shift_imm;
mod sve_unpack;
mod sve_whilelo;
mod sve_word_load_store;
mod sve_xar;
mod sve_z_vector;
mod system_extensions;
mod system_flags;
mod system_misc;
mod system_wait_barrier;
mod system_undefined;

fn assert_decode_cases(cases: &[(u32, Opcode, &str)]) {
    for &(raw, expected, mnemonic) in cases {
        assert_disarm64_mnemonic(raw, mnemonic);
        assert_eq!(decode(raw).unwrap().op, expected, "raw=0x{raw:08x}");
    }
}

fn assert_disarm64_mnemonic(raw: u32, mnemonic: &str) {
    let decoded = disarm64::decoder::decode(raw).expect("disarm64 should decode test word");
    assert_eq!(format!("{:?}", decoded.mnemonic), mnemonic);
}
