use super::*;

#[test]
fn decode_simd_userland_arithmetic_move_and_shift_forms() {
    assert_eq!(decode(0x4E22_BC45).unwrap().op, Opcode::SimdAddp);
    let addp_scalar = decode(0x5EF1_BB9F).unwrap();
    assert_eq!(addp_scalar.op, Opcode::SimdAddp);
    assert_eq!(addp_scalar.rd, 31);
    assert_eq!(addp_scalar.rn, 28);
    assert_eq!(addp_scalar.rm, 0xFF);
    assert_eq!(addp_scalar.imm, 8);
    assert_eq!(addp_scalar.size, 8);
    assert!(decode(0x0EE0_BC00).is_none());
    assert_eq!(decode(0x6E1F_43FF).unwrap().op, Opcode::SimdExt);
    assert_eq!(decode(0x6E20_5BDE).unwrap().op, Opcode::SimdNot);
    assert_eq!(decode(0x4EFE_87FF).unwrap().op, Opcode::SimdAddVec);
    let add_scalar_d = decode(0x5EFF_85EF).unwrap();
    assert_eq!(add_scalar_d.op, Opcode::SimdAddVec);
    assert_eq!(add_scalar_d.rd, 15);
    assert_eq!(add_scalar_d.rn, 15);
    assert_eq!(add_scalar_d.rm, 31);
    assert_eq!(add_scalar_d.imm, 8);
    assert_eq!(add_scalar_d.size, 8);
    let add_scalar_d_alt = decode(0x5EFF_87BD).unwrap();
    assert_eq!(add_scalar_d_alt.op, Opcode::SimdAddVec);
    assert_eq!(add_scalar_d_alt.rd, 29);
    assert_eq!(add_scalar_d_alt.rn, 29);
    assert_eq!(add_scalar_d_alt.rm, 31);
    assert_eq!(add_scalar_d_alt.imm, 8);
    assert_eq!(add_scalar_d_alt.size, 8);
    assert!(decode(0x5E20_8400).is_none());
    assert_eq!(decode(0x1E26_03E1).unwrap().op, Opcode::SimdFmovSToGpr);
    assert_eq!(decode(0x1E27_009F).unwrap().op, Opcode::SimdFmovGprToS);
    let fmov_lane_insert = decode(0x9EAF_0060).unwrap();
    assert_eq!(fmov_lane_insert.op, Opcode::SimdInsGprLane);
    assert_eq!(fmov_lane_insert.rd, 0);
    assert_eq!(fmov_lane_insert.rn, 3);
    assert_eq!(fmov_lane_insert.imm, 1);
    assert_eq!(decode(0x4D40_CC1F).unwrap().op, Opcode::SimdLd1r);
    assert_eq!(decode(0x6F3C_07BD).unwrap().op, Opcode::SimdUshr);
    assert_eq!(decode(0x4EB6_8FDF).unwrap().op, Opcode::SimdCmtst);
    assert_eq!(decode(0x0EA1_2BEF).unwrap().op, Opcode::SimdXtn);
    assert_eq!(decode(0x6E07_079F).unwrap().op, Opcode::SimdInsElem);
    assert_eq!(decode(0x6E20_0BFF).unwrap().op, Opcode::SimdRev32);
    let rev64 = decode(0x0EA0_0BDE).unwrap();
    assert_eq!(rev64.op, Opcode::SimdRev64);
    assert_eq!(rev64.rd, 30);
    assert_eq!(rev64.rn, 30);
    assert_eq!(rev64.imm, 4);
    assert_eq!(rev64.size, 8);
    assert_eq!(decode(0x0F2D_57C2).unwrap().op, Opcode::SimdShlImm);
    let sli = decode(0x6F39_5486).unwrap();
    assert_eq!(sli.op, Opcode::SimdSli);
    assert_eq!(sli.rd, 6);
    assert_eq!(sli.rn, 4);
    assert_eq!(sli.imm, 25);
    assert_eq!(sli.cond, 4);
    assert_eq!(sli.size, 16);
    let sri = decode(0x6F0F_47DF).unwrap();
    assert_eq!(sri.op, Opcode::SimdSri);
    assert_eq!(sri.rd, 31);
    assert_eq!(sri.rn, 30);
    assert_eq!(sri.imm, 1);
    assert_eq!(sri.cond, 1);
    assert_eq!(sri.size, 16);
    let sshr_words = decode(0x0F38_07FC).unwrap();
    assert_eq!(sshr_words.op, Opcode::SimdSshr);
    assert_eq!(sshr_words.rd, 28);
    assert_eq!(sshr_words.rn, 31);
    assert_eq!(sshr_words.imm, 8);
    assert_eq!(sshr_words.cond, 4);
    assert_eq!(sshr_words.size, 8);
    let sshr_doublewords = decode(0x4F41_0561).unwrap();
    assert_eq!(sshr_doublewords.op, Opcode::SimdSshr);
    assert_eq!(sshr_doublewords.imm, 63);
    assert_eq!(sshr_doublewords.cond, 8);
    assert_eq!(sshr_doublewords.size, 16);
    let sshr_scalar = decode(0x5F70_07FD).unwrap();
    assert_eq!(sshr_scalar.op, Opcode::SimdSshr);
    assert_eq!(sshr_scalar.rd, 29);
    assert_eq!(sshr_scalar.rn, 31);
    assert_eq!(sshr_scalar.imm, 16);
    assert_eq!(sshr_scalar.cond, 8);
    assert_eq!(sshr_scalar.size, 8);
    assert!(decode(0x5F00_0400).is_none());
    assert!(decode(0x0F40_0400).is_none());
    assert!(decode(0x2F40_0400).is_none());
    let shrn = decode(0x0F0A_87FF).unwrap();
    assert_eq!(shrn.op, Opcode::SimdShrn);
    assert_eq!(shrn.rd, 31);
    assert_eq!(shrn.rn, 31);
    assert_eq!(shrn.imm, 6);
    assert_eq!(shrn.cond, 1);
    assert_eq!(shrn.size, 8);
    let shrn_strlen = decode(0x0F0C_8422).unwrap();
    assert_eq!(shrn_strlen.op, Opcode::SimdShrn);
    assert_eq!(shrn_strlen.imm, 4);
    assert_eq!(shrn_strlen.cond, 1);
    assert_eq!(decode(0x4E08_077D).unwrap().op, Opcode::SimdDupElem);
    let ushl = decode(0x6EF9_47BD).unwrap();
    assert_eq!(ushl.op, Opcode::SimdUshl);
    assert_eq!(ushl.imm, 8);
    assert_eq!(ushl.size, 16);
    let ushl_scalar = decode(0x7EFF_47DF).unwrap();
    assert_eq!(ushl_scalar.op, Opcode::SimdUshl);
    assert_eq!(ushl_scalar.rd, 31);
    assert_eq!(ushl_scalar.rn, 30);
    assert_eq!(ushl_scalar.rm, 31);
    assert_eq!(ushl_scalar.imm, 8);
    assert_eq!(ushl_scalar.size, 8);
    assert!(decode(0x2EFF_47DF).is_none());
    assert_eq!(decode(0x4E9C_1BDE).unwrap().op, Opcode::SimdUzp1);
    let zip1_bytes = decode(0x4E1B_3BFD).unwrap();
    assert_eq!(zip1_bytes.op, Opcode::SimdZip1);
    assert_eq!(zip1_bytes.rd, 29);
    assert_eq!(zip1_bytes.rn, 31);
    assert_eq!(zip1_bytes.rm, 27);
    assert_eq!(zip1_bytes.imm, 1);
    let zip2_halfwords = decode(0x4E5B_7BFF).unwrap();
    assert_eq!(zip2_halfwords.op, Opcode::SimdZip2);
    assert_eq!(zip2_halfwords.rd, 31);
    assert_eq!(zip2_halfwords.rn, 31);
    assert_eq!(zip2_halfwords.rm, 27);
    assert_eq!(zip2_halfwords.imm, 2);
    let trn1_doublewords = decode(0x4ECD_296D).unwrap();
    assert_eq!(trn1_doublewords.op, Opcode::SimdTrn1);
    assert_eq!(trn1_doublewords.rd, 13);
    assert_eq!(trn1_doublewords.rn, 11);
    assert_eq!(trn1_doublewords.rm, 13);
    assert_eq!(trn1_doublewords.imm, 8);
    assert_eq!(trn1_doublewords.size, 16);
    assert!(decode(0x0EC0_2800).is_none());
    let tbl = decode(0x4E17_03FF).unwrap();
    assert_eq!(tbl.op, Opcode::SimdTbl);
    assert_eq!(tbl.rd, 31);
    assert_eq!(tbl.rn, 31);
    assert_eq!(tbl.rm, 23);
    assert_eq!(tbl.cond, 1);
    assert_eq!(tbl.size, 16);
    let aese = decode(0x4E28_4806).unwrap();
    assert_eq!(aese.op, Opcode::SimdAese);
    assert_eq!(aese.rd, 6);
    assert_eq!(aese.rn, 0);
    assert_eq!(aese.size, 16);
    let aesd = decode(0x4E28_5802).unwrap();
    assert_eq!(aesd.op, Opcode::SimdAesd);
    assert_eq!(aesd.rd, 2);
    assert_eq!(aesd.rn, 0);
    let aesmc = decode(0x4E28_6842).unwrap();
    assert_eq!(aesmc.op, Opcode::SimdAesmc);
    assert_eq!(aesmc.rd, 2);
    assert_eq!(aesmc.rn, 2);
    let aesimc = decode(0x4E28_7800).unwrap();
    assert_eq!(aesimc.op, Opcode::SimdAesimc);
    assert_eq!(aesimc.rd, 0);
    assert_eq!(aesimc.rn, 0);
}
