use super::*;

#[test]
fn decode_simd_userland_structure_load_store_forms() {
    let ld1_post_two = decode(0x4CDF_A03C).unwrap();
    assert_eq!(ld1_post_two.op, Opcode::SimdLd1Multi);
    assert_eq!(ld1_post_two.cond, 2);
    assert_eq!(ld1_post_two.imm, 32);
    let ld1_post_three = decode(0x4CDF_603C).unwrap();
    assert_eq!(ld1_post_three.op, Opcode::SimdLd1Multi);
    assert_eq!(ld1_post_three.cond, 3);
    assert_eq!(ld1_post_three.imm, 48);
    let ld1_post_four = decode(0x4CDF_203C).unwrap();
    assert_eq!(ld1_post_four.op, Opcode::SimdLd1Multi);
    assert_eq!(ld1_post_four.cond, 4);
    assert_eq!(ld1_post_four.imm, 64);
    let ld2 = decode(0x4C40_803C).unwrap();
    assert_eq!(ld2.op, Opcode::SimdLd2);
    assert_eq!(ld2.rd, 28);
    assert_eq!(ld2.rn, 1);
    assert_eq!(ld2.cond, 0);
    assert_eq!(ld2.size, 16);
    let ld2_half = decode(0x4C40_863C).unwrap();
    assert_eq!(ld2_half.op, Opcode::SimdLd2);
    assert_eq!(ld2_half.rd, 28);
    assert_eq!(ld2_half.rn, 17);
    assert_eq!(ld2_half.cond, 1);
    let ld2_post_reg = decode(0x4CC8_803C).unwrap();
    assert_eq!(ld2_post_reg.op, Opcode::SimdLd2);
    assert_eq!(ld2_post_reg.rm, 8);
    assert_eq!(ld2_post_reg.imm, 0);
    let ld3 = decode(0x4C40_4C5D).unwrap();
    assert_eq!(ld3.op, Opcode::SimdLd3);
    assert_eq!(ld3.rd, 29);
    assert_eq!(ld3.rn, 2);
    assert_eq!(ld3.cond, 3);
    let ld3_post_imm = decode(0x4CDF_4C5A).unwrap();
    assert_eq!(ld3_post_imm.op, Opcode::SimdLd3);
    assert_eq!(ld3_post_imm.rd, 26);
    assert_eq!(ld3_post_imm.rn, 2);
    assert_eq!(ld3_post_imm.imm, 48);
    let post_index_st1 = decode(0x4C9F_AA24).unwrap();
    assert_eq!(post_index_st1.op, Opcode::SimdSt1Multi);
    assert_eq!(post_index_st1.rd, 4);
    assert_eq!(post_index_st1.rn, 17);
    assert_eq!(post_index_st1.imm, 32);
    assert_eq!(post_index_st1.cond, 2);
    assert_eq!(post_index_st1.size, 16);
    let st1_one = decode(0x4C00_7020).unwrap();
    assert_eq!(st1_one.op, Opcode::SimdSt1Multi);
    assert_eq!(st1_one.rd, 0);
    assert_eq!(st1_one.rn, 1);
    assert_eq!(st1_one.cond, 1);
    assert_eq!(st1_one.size, 16);
    let post_index_st1_one = decode(0x4C9F_7A24).unwrap();
    assert_eq!(post_index_st1_one.op, Opcode::SimdSt1Multi);
    assert_eq!(post_index_st1_one.rd, 4);
    assert_eq!(post_index_st1_one.rn, 17);
    assert_eq!(post_index_st1_one.imm, 16);
    assert_eq!(post_index_st1_one.cond, 1);
    assert_eq!(post_index_st1_one.size, 16);
    let st1_one_q0 = decode(0x0C9F_795D).unwrap();
    assert_eq!(st1_one_q0.op, Opcode::SimdSt1Multi);
    assert_eq!(st1_one_q0.rd, 29);
    assert_eq!(st1_one_q0.rn, 10);
    assert_eq!(st1_one_q0.imm, 8);
    assert_eq!(st1_one_q0.size, 8);
    let st1_one_post_reg = decode(0x4C84_7800).unwrap();
    assert_eq!(st1_one_post_reg.op, Opcode::SimdSt1Multi);
    assert_eq!(st1_one_post_reg.rd, 0);
    assert_eq!(st1_one_post_reg.rn, 0);
    assert_eq!(st1_one_post_reg.rm, 4);
    assert_eq!(st1_one_post_reg.imm, 0);
    let ld1_lane_byte = decode(0x0D40_0C7E).unwrap();
    assert_eq!(ld1_lane_byte.op, Opcode::SimdLd1Lane);
    assert_eq!(ld1_lane_byte.rd, 30);
    assert_eq!(ld1_lane_byte.rn, 3);
    assert_eq!(ld1_lane_byte.imm, 3);
    assert_eq!(ld1_lane_byte.cond, 1);
    assert_eq!(ld1_lane_byte.size, 1);
    let st1_lane_half = decode(0x0D00_527C).unwrap();
    assert_eq!(st1_lane_half.op, Opcode::SimdSt1Lane);
    assert_eq!(st1_lane_half.rd, 28);
    assert_eq!(st1_lane_half.rn, 19);
    assert_eq!(st1_lane_half.imm, 2);
    assert_eq!(st1_lane_half.cond, 2);
    assert_eq!(st1_lane_half.size, 2);
    let st1_lane_post_word = decode(0x0D9F_80E6).unwrap();
    assert_eq!(st1_lane_post_word.op, Opcode::SimdSt1Lane);
    assert_eq!(st1_lane_post_word.rd, 6);
    assert_eq!(st1_lane_post_word.rn, 7);
    assert_eq!(st1_lane_post_word.rm, 0xFE);
    assert_eq!(st1_lane_post_word.imm, 0);
    assert_eq!(st1_lane_post_word.cond, 4);
    assert_eq!(st1_lane_post_word.size, 4);
    let st1_lane_post_reg = decode(0x0D84_80E6).unwrap();
    assert_eq!(st1_lane_post_reg.op, Opcode::SimdSt1Lane);
    assert_eq!(st1_lane_post_reg.rm, 4);
    assert_eq!(st1_lane_post_reg.imm, 0);
    assert_eq!(st1_lane_post_reg.cond, 4);
    let ld1_lane_post_reg = decode(0x0DC4_80E6).unwrap();
    assert_eq!(ld1_lane_post_reg.op, Opcode::SimdLd1Lane);
    assert_eq!(ld1_lane_post_reg.rm, 4);
    assert_eq!(ld1_lane_post_reg.imm, 0);
    assert_eq!(ld1_lane_post_reg.cond, 4);
    let ld1_lane_double = decode(0x4D40_8400).unwrap();
    assert_eq!(ld1_lane_double.op, Opcode::SimdLd1Lane);
    assert_eq!(ld1_lane_double.imm, 1);
    assert_eq!(ld1_lane_double.cond, 8);
    let ld4 = decode(0x4C40_003C).unwrap();
    assert_eq!(ld4.op, Opcode::SimdLd4);
    assert_eq!(ld4.rd, 28);
    assert_eq!(ld4.rn, 1);
    assert_eq!(ld4.cond, 0);
    assert_eq!(ld4.size, 16);
    let ld4_post_imm = decode(0x4CDF_003C).unwrap();
    assert_eq!(ld4_post_imm.op, Opcode::SimdLd4);
    assert_eq!(ld4_post_imm.rd, 28);
    assert_eq!(ld4_post_imm.rn, 1);
    assert_eq!(ld4_post_imm.rm, 0xFE);
    assert_eq!(ld4_post_imm.imm, 64);
    assert_eq!(ld4_post_imm.size, 16);
    let ld4_post_reg = decode(0x4CC2_003C).unwrap();
    assert_eq!(ld4_post_reg.op, Opcode::SimdLd4);
    assert_eq!(ld4_post_reg.rm, 2);
    assert_eq!(ld4_post_reg.imm, 0);
    assert!(decode(0x0C40_0C3C).is_none());
}
