use super::*;

#[test]
fn decode_simd_userland_fp_immediate_and_compare_forms() {
    let simd_fcvtzu = decode(0x7EE1_B800).unwrap();
    assert_eq!(simd_fcvtzu.op, Opcode::SimdFcvtzu);
    assert_eq!(simd_fcvtzu.rd, 0);
    assert_eq!(simd_fcvtzu.rn, 0);
    assert_eq!(simd_fcvtzu.size, 8);
    let simd_scvtf_scalar = decode(0x5E61_DBFF).unwrap();
    assert_eq!(simd_scvtf_scalar.op, Opcode::SimdScvtf);
    assert_eq!(simd_scvtf_scalar.rd, 31);
    assert_eq!(simd_scvtf_scalar.rn, 31);
    assert_eq!(simd_scvtf_scalar.imm, 8);
    assert_eq!(simd_scvtf_scalar.size, 8);
    let simd_fcvtzs_scalar = decode(0x5EA1_B9EF).unwrap();
    assert_eq!(simd_fcvtzs_scalar.op, Opcode::SimdFcvtzs);
    assert_eq!(simd_fcvtzs_scalar.rd, 15);
    assert_eq!(simd_fcvtzs_scalar.rn, 15);
    assert_eq!(simd_fcvtzs_scalar.imm, 4);
    assert_eq!(simd_fcvtzs_scalar.size, 4);
    let simd_scvtf_vec = decode(0x4E61_D800).unwrap();
    assert_eq!(simd_scvtf_vec.op, Opcode::SimdScvtf);
    assert_eq!(simd_scvtf_vec.imm, 8);
    assert_eq!(simd_scvtf_vec.size, 16);
    let simd_fcvtzs_vec = decode(0x4EA1_B800).unwrap();
    assert_eq!(simd_fcvtzs_vec.op, Opcode::SimdFcvtzs);
    assert_eq!(simd_fcvtzs_vec.imm, 4);
    assert_eq!(simd_fcvtzs_vec.size, 16);
    assert_ne!(
        decode(0x7F5B_FFB3).map(|instr| instr.op),
        Some(Opcode::SimdLdr)
    );
    assert!(decode(0x0E61_D800).is_none());
    assert!(decode(0x0EE1_B800).is_none());
    assert_eq!(decode(0x0F00_043F).unwrap().op, Opcode::SimdMovi);
    let movi_doubleword = decode(0x2F07_E61F).unwrap();
    assert_eq!(movi_doubleword.op, Opcode::SimdMovi);
    assert_eq!(movi_doubleword.rd, 31);
    assert_eq!(movi_doubleword.imm, 0xffff_ffff_0000_0000);
    assert_eq!(movi_doubleword.cond, 8);
    assert_eq!(movi_doubleword.size, 8);
    let movi_half = decode(0x0F00_848F).unwrap();
    assert_eq!(movi_half.op, Opcode::SimdMovi);
    assert_eq!(movi_half.rd, 15);
    assert_eq!(movi_half.imm, 4);
    assert_eq!(movi_half.cond, 2);
    let movi_half_shift = decode(0x0F04_A41F).unwrap();
    assert_eq!(movi_half_shift.op, Opcode::SimdMovi);
    assert_eq!(movi_half_shift.imm, 0x8000);
    assert_eq!(movi_half_shift.cond, 2);
    let movi_bytes = decode(0x0F03_E7FF).unwrap();
    assert_eq!(movi_bytes.op, Opcode::SimdMovi);
    assert_eq!(movi_bytes.rd, 31);
    assert_eq!(movi_bytes.imm, 0x7f);
    assert_eq!(movi_bytes.cond, 0);
    assert_eq!(movi_bytes.size, 8);
    assert_eq!(decode(0x2F00_051E).unwrap().op, Opcode::SimdMvni);
    let mvni_half_shift = decode(0x2F04_A480).unwrap();
    assert_eq!(mvni_half_shift.op, Opcode::SimdMvni);
    assert_eq!(mvni_half_shift.rd, 0);
    assert_eq!(mvni_half_shift.imm, 0x8400);
    assert_eq!(mvni_half_shift.cond, 2);
    assert_eq!(mvni_half_shift.size, 8);
    let mvni_half = decode(0x2F03_87E0).unwrap();
    assert_eq!(mvni_half.op, Opcode::SimdMvni);
    assert_eq!(mvni_half.imm, 0x7f);
    assert_eq!(mvni_half.cond, 2);
    let mvni_msl = decode(0x2F03_D7FE).unwrap();
    assert_eq!(mvni_msl.op, Opcode::SimdMvni);
    assert_eq!(mvni_msl.rd, 30);
    assert_eq!(mvni_msl.imm, 0x007f_ffff);
    assert_eq!(mvni_msl.cond, 4);
    assert_eq!(mvni_msl.size, 8);
    assert_eq!(decode(0x6E22_AC20).unwrap().op, Opcode::SimdUminp);
    let umin_vec = decode(0x2EBE_6FFF).unwrap();
    assert_eq!(umin_vec.op, Opcode::SimdUminVec);
    assert_eq!(umin_vec.rd, 31);
    assert_eq!(umin_vec.rn, 31);
    assert_eq!(umin_vec.rm, 30);
    assert_eq!(umin_vec.imm, 4);
    assert_eq!(umin_vec.size, 8);
    let umax_vec = decode(0x6EBF_67BD).unwrap();
    assert_eq!(umax_vec.op, Opcode::SimdUmaxVec);
    assert_eq!(umax_vec.rd, 29);
    assert_eq!(umax_vec.rn, 29);
    assert_eq!(umax_vec.rm, 31);
    assert_eq!(umax_vec.imm, 4);
    assert_eq!(umax_vec.size, 16);
    let smax_vec = decode(0x0EBF_67DF).unwrap();
    assert_eq!(smax_vec.op, Opcode::SimdSmaxVec);
    assert_eq!(smax_vec.rd, 31);
    assert_eq!(smax_vec.rn, 30);
    assert_eq!(smax_vec.rm, 31);
    assert_eq!(smax_vec.imm, 4);
    assert_eq!(smax_vec.size, 8);
    assert!(decode(0x2EE0_6400).is_none());
    assert!(decode(0x0EE0_6400).is_none());
    assert_eq!(decode(0x0E20_9800).unwrap().op, Opcode::SimdCmeqZero);
    let cmeq_zero_scalar = decode(0x5EE0_9BFF).unwrap();
    assert_eq!(cmeq_zero_scalar.op, Opcode::SimdCmeqZero);
    assert_eq!(cmeq_zero_scalar.rd, 31);
    assert_eq!(cmeq_zero_scalar.rn, 31);
    assert_eq!(cmeq_zero_scalar.imm, 8);
    assert_eq!(cmeq_zero_scalar.size, 8);
    assert!(decode(0x5EA0_9800).is_none());
    assert!(decode(0x0EE0_9800).is_none());
    let cmeq_words = decode(0x6EB9_8FFF).unwrap();
    assert_eq!(cmeq_words.op, Opcode::SimdCmeqReg);
    assert_eq!(cmeq_words.rd, 31);
    assert_eq!(cmeq_words.rn, 31);
    assert_eq!(cmeq_words.rm, 25);
    assert_eq!(cmeq_words.imm, 4);
    assert_eq!(cmeq_words.size, 16);
    let cmhi_words = decode(0x6EBD_37FD).unwrap();
    assert_eq!(cmhi_words.op, Opcode::SimdCmhiReg);
    assert_eq!(cmhi_words.rd, 29);
    assert_eq!(cmhi_words.rn, 31);
    assert_eq!(cmhi_words.rm, 29);
    assert_eq!(cmhi_words.imm, 4);
    assert_eq!(cmhi_words.size, 16);
    let cmhi_doublewords = decode(0x6EFD_37FC).unwrap();
    assert_eq!(cmhi_doublewords.op, Opcode::SimdCmhiReg);
    assert_eq!(cmhi_doublewords.imm, 8);
    assert_eq!(cmhi_doublewords.size, 16);
    let cmhi_scalar = decode(0x7EFF_37DF).unwrap();
    assert_eq!(cmhi_scalar.op, Opcode::SimdCmhiReg);
    assert_eq!(cmhi_scalar.rd, 31);
    assert_eq!(cmhi_scalar.rn, 30);
    assert_eq!(cmhi_scalar.rm, 31);
    assert_eq!(cmhi_scalar.imm, 8);
    assert_eq!(cmhi_scalar.size, 8);
    assert!(decode(0x2EE0_3400).is_none());
    let uqsub = decode(0x7E6F_2FFF).unwrap();
    assert_eq!(uqsub.op, Opcode::SimdUqsub);
    assert_eq!(uqsub.rd, 31);
    assert_eq!(uqsub.rn, 31);
    assert_eq!(uqsub.rm, 15);
    assert_eq!(uqsub.imm, 2);
    assert_eq!(uqsub.size, 2);
}
