use super::*;

#[test]
fn decode_simd_userland_widening_crypto_and_fp_forms() {
    let shll = decode(0x2E21_3BDE).unwrap();
    assert_eq!(shll.op, Opcode::SimdShll);
    assert_eq!(shll.rd, 30);
    assert_eq!(shll.rn, 30);
    assert_eq!(shll.imm, 8);
    assert_eq!(shll.cond, 1);
    assert!(!shll.sf);
    let shll2 = decode(0x6E61_3A21).unwrap();
    assert_eq!(shll2.op, Opcode::SimdShll);
    assert_eq!(shll2.rd, 1);
    assert_eq!(shll2.rn, 17);
    assert_eq!(shll2.imm, 16);
    assert_eq!(shll2.cond, 2);
    assert!(shll2.sf);
    let saddl = decode(0x0EB9_02D0).unwrap();
    assert_eq!(saddl.op, Opcode::SimdSaddl);
    assert_eq!(saddl.rd, 16);
    assert_eq!(saddl.rn, 22);
    assert_eq!(saddl.rm, 25);
    assert_eq!(saddl.cond, 4);
    assert!(!saddl.sf);
    let saddl2 = decode(0x4EB9_02D6).unwrap();
    assert_eq!(saddl2.op, Opcode::SimdSaddl);
    assert_eq!(saddl2.rd, 22);
    assert_eq!(saddl2.rn, 22);
    assert_eq!(saddl2.rm, 25);
    assert_eq!(saddl2.cond, 4);
    assert!(saddl2.sf);
    let usubl = decode(0x2EBD_23FE).unwrap();
    assert_eq!(usubl.op, Opcode::SimdUsubl);
    assert_eq!(usubl.rd, 30);
    assert_eq!(usubl.rn, 31);
    assert_eq!(usubl.rm, 29);
    assert_eq!(usubl.cond, 4);
    assert!(!usubl.sf);
    let usubl2 = decode(0x6EBD_23FF).unwrap();
    assert_eq!(usubl2.op, Opcode::SimdUsubl);
    assert_eq!(usubl2.rd, 31);
    assert_eq!(usubl2.rn, 31);
    assert_eq!(usubl2.rm, 29);
    assert_eq!(usubl2.cond, 4);
    assert!(usubl2.sf);
    let ssubw = decode(0x0E7E_33BD).unwrap();
    assert_eq!(ssubw.op, Opcode::SimdSsubw);
    assert_eq!(ssubw.rd, 29);
    assert_eq!(ssubw.rn, 29);
    assert_eq!(ssubw.rm, 30);
    assert_eq!(ssubw.cond, 2);
    assert!(!ssubw.sf);
    let ssubw2 = decode(0x4E7E_33FF).unwrap();
    assert_eq!(ssubw2.op, Opcode::SimdSsubw);
    assert_eq!(ssubw2.rd, 31);
    assert_eq!(ssubw2.rn, 31);
    assert_eq!(ssubw2.rm, 30);
    assert_eq!(ssubw2.cond, 2);
    assert!(ssubw2.sf);
    let umlal = decode(0x2F80_2386).unwrap();
    assert_eq!(umlal.op, Opcode::SimdUmlal);
    assert_eq!(umlal.rd, 6);
    assert_eq!(umlal.rn, 28);
    assert_eq!(umlal.rm, 0);
    assert_eq!(umlal.imm, 0);
    assert_eq!(umlal.cond, 4);
    assert_eq!(umlal.size, 16);
    let umlal_lane3 = decode(0x2FA0_2B89).unwrap();
    assert_eq!(umlal_lane3.op, Opcode::SimdUmlal);
    assert_eq!(umlal_lane3.imm, 3);
    assert_eq!(umlal_lane3.cond, 4);
    let umlal2 = decode(0x6F80_2386).unwrap();
    assert_eq!(umlal2.op, Opcode::SimdUmlal);
    assert!(umlal2.sf);
    let neg_vec = decode(0x6EA0_BBFF).unwrap();
    assert_eq!(neg_vec.op, Opcode::SimdNeg);
    assert_eq!(neg_vec.rd, 31);
    assert_eq!(neg_vec.rn, 31);
    assert_eq!(neg_vec.imm, 4);
    assert_eq!(neg_vec.size, 16);
    let abs_vec = decode(0x4EE0_BBDE).unwrap();
    assert_eq!(abs_vec.op, Opcode::SimdAbs);
    assert_eq!(abs_vec.rd, 30);
    assert_eq!(abs_vec.rn, 30);
    assert_eq!(abs_vec.imm, 8);
    assert_eq!(abs_vec.size, 16);
    let abs_scalar = decode(0x5EE0_BB00).unwrap();
    assert_eq!(abs_scalar.op, Opcode::SimdAbs);
    assert_eq!(abs_scalar.rd, 0);
    assert_eq!(abs_scalar.rn, 24);
    assert_eq!(abs_scalar.imm, 8);
    assert_eq!(abs_scalar.size, 8);
    assert!(decode(0x0EE0_BB00).is_none());
    assert!(decode(0x5E20_BB00).is_none());
    let neg_scalar = decode(0x7EE0_BBFF).unwrap();
    assert_eq!(neg_scalar.op, Opcode::SimdNeg);
    assert_eq!(neg_scalar.imm, 8);
    assert_eq!(neg_scalar.size, 8);
    assert_eq!(decode(0x7E20_BBE1).unwrap().op, Opcode::SimdNeg);
    assert!(decode(0x2EE0_BBE1).is_none());
    assert_eq!(decode(0x6EE0_FBFF).unwrap().op, Opcode::SimdFpNeg);
    let fadd_vec = decode(0x4E20_D400).unwrap();
    assert_eq!(fadd_vec.op, Opcode::SimdFpAddVec);
    assert_eq!(fadd_vec.imm, 4);
    assert_eq!(fadd_vec.size, 16);
    let fsub_vec = decode(0x4EA3_D441).unwrap();
    assert_eq!(fsub_vec.op, Opcode::SimdFpSubVec);
    assert_eq!(fsub_vec.rd, 1);
    assert_eq!(fsub_vec.rn, 2);
    assert_eq!(fsub_vec.rm, 3);
    let fmul_vec = decode(0x6E26_DCA4).unwrap();
    assert_eq!(fmul_vec.op, Opcode::SimdFpMulVec);
    assert_eq!(fmul_vec.size, 16);
    let fdiv_vec = decode(0x6E7C_FF7B).unwrap();
    assert_eq!(fdiv_vec.op, Opcode::SimdFpDivVec);
    assert_eq!(fdiv_vec.rd, 27);
    assert_eq!(fdiv_vec.rn, 27);
    assert_eq!(fdiv_vec.rm, 28);
    assert_eq!(fdiv_vec.imm, 8);
    assert_eq!(fdiv_vec.size, 16);
    let fabd_scalar = decode(0x7EE9_D7FF).unwrap();
    assert_eq!(fabd_scalar.op, Opcode::SimdFpAbd);
    assert_eq!(fabd_scalar.rd, 31);
    assert_eq!(fabd_scalar.rn, 31);
    assert_eq!(fabd_scalar.rm, 9);
    assert_eq!(fabd_scalar.imm, 8);
    assert_eq!(fabd_scalar.size, 8);
    let fabd_vec = decode(0x6EA2_D420).unwrap();
    assert_eq!(fabd_vec.op, Opcode::SimdFpAbd);
    assert_eq!(fabd_vec.imm, 4);
    assert_eq!(fabd_vec.size, 16);
    let fnmul = decode(0x1E7F_8800).unwrap();
    assert_eq!(fnmul.op, Opcode::FpFnmul);
    assert_eq!(fnmul.rd, 0);
    assert_eq!(fnmul.rn, 0);
    assert_eq!(fnmul.rm, 31);
    assert_eq!(fnmul.size, 8);
    assert!(decode(0x0E60_D400).is_none());
    assert!(decode(0x0E60_FC00).is_none());
    assert!(decode(0x1EA1_8800).is_none());
    assert_eq!(decode(0x6EFD_87FF).unwrap().op, Opcode::SimdSubVec);
}
