use super::*;

pub(in crate::arm64::machine) fn is_simd_integer_opcode(op: Opcode) -> bool {
    matches!(
        op,
        Opcode::SimdDupByte
            | Opcode::SimdDupElem
            | Opcode::SimdFmovReg64
            | Opcode::SimdFmovGprToD
            | Opcode::SimdFmovGprToS
            | Opcode::SimdFmovDToGpr
            | Opcode::SimdFmovSToGpr
            | Opcode::SimdFmovLaneToGpr
            | Opcode::SimdFmovImm
            | Opcode::SimdUmov
            | Opcode::SimdSmov
            | Opcode::SimdInsGprLane
            | Opcode::SimdCmeqZero
            | Opcode::SimdCmgtZero
            | Opcode::SimdCmgeZero
            | Opcode::SimdCmleZero
            | Opcode::SimdCmltZero
            | Opcode::SimdCmeqReg
            | Opcode::SimdCmgtReg
            | Opcode::SimdCmgeReg
            | Opcode::SimdCmhsReg
            | Opcode::SimdCmhiReg
            | Opcode::SimdShrn
            | Opcode::SimdShrn2
            | Opcode::SimdRshrn
            | Opcode::SimdRshrn2
            | Opcode::SimdAddhn
            | Opcode::SimdAddhn2
            | Opcode::SimdRaddhn
            | Opcode::SimdRaddhn2
            | Opcode::SimdSubhn
            | Opcode::SimdSubhn2
            | Opcode::SimdRsubhn
            | Opcode::SimdRsubhn2
            | Opcode::SimdAddVec
            | Opcode::SimdSubVec
            | Opcode::SimdMulVec
            | Opcode::SimdMlaVec
            | Opcode::SimdAddp
            | Opcode::SimdAddv
            | Opcode::SimdSmaxv
            | Opcode::SimdSminv
            | Opcode::SimdUmaxv
            | Opcode::SimdUminv
            | Opcode::SimdExt
            | Opcode::SimdSmaxVec
            | Opcode::SimdSminVec
            | Opcode::SimdUmaxVec
            | Opcode::SimdUminVec
            | Opcode::SimdSmaxp
            | Opcode::SimdSminp
            | Opcode::SimdUmaxp
            | Opcode::SimdUminp
            | Opcode::SimdCnt
            | Opcode::SimdCmtst
            | Opcode::SimdShlImm
            | Opcode::SimdSli
            | Opcode::SimdSri
            | Opcode::SimdSshr
            | Opcode::SimdUshr
            | Opcode::SimdUshl
            | Opcode::SimdXtn
            | Opcode::SimdXtn2
            | Opcode::SimdRev64
            | Opcode::SimdRev32
            | Opcode::SimdNot
            | Opcode::SimdBsl
            | Opcode::SimdBit
            | Opcode::SimdBif
            | Opcode::SimdAnd
            | Opcode::SimdBic
            | Opcode::SimdOrr
            | Opcode::SimdOrn
            | Opcode::SimdEor
            | Opcode::SimdInsElem
            | Opcode::SimdUzp1
            | Opcode::SimdUzp2
            | Opcode::SimdTrn1
            | Opcode::SimdTrn2
            | Opcode::SimdZip1
            | Opcode::SimdZip2
            | Opcode::SimdTbl
            | Opcode::SimdBicImm
            | Opcode::SimdMvni
            | Opcode::SimdUshll
            | Opcode::SimdSshll
            | Opcode::SimdShll
            | Opcode::SimdSaddl
            | Opcode::SimdUsubl
            | Opcode::SimdSsubw
            | Opcode::SimdUmlal
            | Opcode::SimdUqsub
            | Opcode::SimdAbs
            | Opcode::SimdNeg
            | Opcode::SimdScvtf
            | Opcode::SimdUcvtf
            | Opcode::SimdFcvtzs
            | Opcode::SimdFcvtzu
            | Opcode::SimdFcvtas
            | Opcode::SimdFpAddVec
            | Opcode::SimdFpSubVec
            | Opcode::SimdFpMulVec
            | Opcode::SimdFpDivVec
            | Opcode::SimdFpAbd
            | Opcode::SimdFpNeg
            | Opcode::SimdFpAbsVec
            | Opcode::SimdFpFrintnVec
            | Opcode::SimdFpFrintaVec
            | Opcode::SimdFpSqrtVec
            | Opcode::SimdFpFacgeVec
            | Opcode::SimdFpFacgtVec
            | Opcode::SimdFpFcmgeVec
            | Opcode::SimdFpFcmgtVec
            | Opcode::SimdFpFcmeqZero
            | Opcode::SimdFpFcmleZero
            | Opcode::SimdFpFcmltZero
            | Opcode::SimdFpFmlaVec
            | Opcode::SimdFpFmlsVec
            | Opcode::SimdFpFmlaElem
            | Opcode::SimdFpFmlsElem
            | Opcode::SimdFpMulElem
            | Opcode::SimdFpFmaxVec
            | Opcode::SimdFpFminVec
            | Opcode::SimdFpFmaxnmVec
            | Opcode::SimdFpFminnmVec
            | Opcode::SimdFpFmaxp
            | Opcode::SimdFpFminp
            | Opcode::SimdFpFmaxnmp
            | Opcode::SimdFpFminnmp
            | Opcode::SimdFpFmaxv
            | Opcode::SimdFpFminv
            | Opcode::SimdFpFmaxnmv
            | Opcode::SimdFpFminnmv
    )
}
