use super::{Instr, Opcode};
use crate::arm64::Armv8Cpu;
use crate::arm64::helpers::{read_base, read_reg};
use crate::arm64::mmu::{Fault, translate, translate_write};
use crate::bus::SystemBus;

mod addsub;
mod count;
mod dup;
mod fp;
mod fp_arith_immediate;
mod fp_compare;
mod fp_convert;
mod fp_fexpa;
mod fp_fscale;
mod fp_ftmad;
mod fp_fused;
mod fp_immediate;
mod fp_indexed;
mod fp_trig_pair;
mod fp_unary;
mod helpers;
mod index;
mod int_compare;
mod logical_imm;
mod logical_pred;
mod memory_b;
mod memory_contiguous;
mod memory_d;
mod memory_register;
mod memory_w;
mod permute;
mod predicate;
mod predicate_bytes;
mod reverse;
mod shift_imm;
mod unpack;
mod vector;
mod xar;

pub(super) use addsub::{exec_sve_addsub_imm, exec_sve_addsub_pred};
pub(super) use count::sve_pred_count;
pub(super) use dup::{exec_sve_dup_elem, exec_sve_dup_imm};
pub(super) use fp::exec_sve_fp_binary;
pub(super) use fp_arith_immediate::{exec_sve_fp_imm, sve_fp_arith_is_immediate};
pub(super) use fp_compare::exec_sve_fp_compare;
pub(super) use fp_convert::exec_sve_fp_convert;
pub(super) use fp_fexpa::exec_sve_fp_fexpa;
pub(super) use fp_fscale::exec_sve_fp_fscale;
pub(super) use fp_ftmad::exec_sve_fp_ftmad;
pub(super) use fp_fused::exec_sve_fp_fused;
pub(super) use fp_immediate::exec_sve_fp_dup_imm;
pub(super) use fp_indexed::exec_sve_fp_indexed;
pub(super) use fp_trig_pair::exec_sve_fp_trig_pair;
pub(super) use fp_unary::exec_sve_fp_unary;
use helpers::*;
pub(super) use index::exec_sve_index;
pub(super) use int_compare::{exec_sve_int_compare, exec_sve_whilelo};
pub(super) use logical_imm::exec_sve_logical_imm;
pub(super) use logical_pred::exec_sve_logical_pred;
pub(super) use memory_b::exec_sve_st1b;
pub(super) use memory_contiguous::exec_sve_contiguous_load;
pub(super) use memory_d::exec_sve_ld1_st1_d;
pub(super) use memory_register::exec_sve_ldr_str;
pub(super) use memory_w::exec_sve_ld1_st1_w;
pub(super) use permute::{exec_sve_tbl, exec_sve_zip};
pub(super) use predicate::{exec_sve_pred_logical, exec_sve_ptest, exec_sve_ptrue, sve_pred_test};
use predicate_bytes::*;
pub(super) use reverse::exec_sve_reverse;
pub(super) use shift_imm::exec_sve_shift_imm;
pub(super) use unpack::exec_sve_unpack;
pub(super) use vector::{
    exec_sve_dup_gpr, exec_sve_int_binary, exec_sve_logical_binary, exec_sve_movprfx, exec_sve_sel,
};
pub(super) use xar::exec_sve_xar;
